name: Pre-Merge Development Validation
on:
  push:
    branches:
      - 'development'
      
jobs:
  format:
    name: Format and Lint Terraform Configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Format and Validate Terrform Configuration
        run: |
          terraform init
          terraform validate -json
          terraform fmt -check -recursive
