name: Main Approve and Apply
on:
  push:
    branches:
      - 'main'

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  # merge-branch:
  #   name: Merge Branch
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: merge-branch
  #       uses: devmasx/merge-branch@master
  #       with: 
  #         type: now
  #         target_branch: 'main'
  #         github_token: ${{ github.token }}

  setup-terraform:
    name: Setup Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1.2.1
        with:
          cli_config_credentials_hostname: 'app.terraform.io'
          cli_config_credentials_token: ${{ secrets.TFC_TOKEN }}
          terraform_version: latest
          terraform_wrapper: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Apply
        id: apply
        run: terraform apply
        continue-on-error: false